import { Inter } from 'next/font/google'
import store from '../lib/store'
import StoreProvider from './StoreProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider store={store}>
      <body className={inter.className}>{children}</body>
      </StoreProvider>
    </html>
  )
}
