export const FETCH_USER = 'FETCH_USER';
export const FETCH_ARTIST_EVENTS = 'FETCH_ARTIST_EVENTS';
export const FETCH_FAV_ARTISTS = 'FETCH_FAV_ARTISTS';
export const FETCH_AUTH_STATUS = 'FETCH_AUTH_STATUS';
export const FETCH_RELATED_ARTISTS = 'FETCH_RELATED_ARTISTS';
export const FETCH_ARTIST = 'FETCH_ARTIST';